-- ============================================
-- مِفتاح | SETUP.sql
-- شغّل الملف كاملًا في Supabase SQL Editor
-- ============================================

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null default 'مستخدم',
  role text not null default 'normal'
    check (role in ('student','normal','admin')),
  plan text not null default 'free'
    check (plan in ('free','pro')),
  pro_until timestamptz,
  xp integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  priority text not null default 'medium'
    check (priority in ('low','medium','high')),
  completed boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.pro_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  payment_reference text not null,
  status text not null default 'pending'
    check (status in ('pending','approved','rejected')),
  reviewed_at timestamptz,
  reviewed_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.tasks enable row level security;
alter table public.pro_requests enable row level security;

-- Remove/recreate policies safely.
drop policy if exists "Users can view own profile" on public.profiles;
drop policy if exists "Users can view own tasks" on public.tasks;
drop policy if exists "Users can update own tasks" on public.tasks;
drop policy if exists "Users can delete own tasks" on public.tasks;
drop policy if exists "Users can view own pro requests" on public.pro_requests;
drop policy if exists "Users can create own pro requests" on public.pro_requests;

create policy "Users can view own profile"
on public.profiles for select to authenticated
using (auth.uid() = id);

create policy "Users can view own tasks"
on public.tasks for select to authenticated
using (auth.uid() = user_id);

create policy "Users can update own tasks"
on public.tasks for update to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete own tasks"
on public.tasks for delete to authenticated
using (auth.uid() = user_id);

create policy "Users can view own pro requests"
on public.pro_requests for select to authenticated
using (auth.uid() = user_id);

create policy "Users can create own pro requests"
on public.pro_requests for insert to authenticated
with check (auth.uid() = user_id);

create unique index if not exists one_pending_pro_request_per_user on public.pro_requests(user_id) where status='pending';

-- Trigger: create a profile automatically after signup.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id,name,role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name','مستخدم'),
    case when new.raw_user_meta_data->>'role'='student' then 'student' else 'normal' end
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Hardened task creation/completion + focus rewards.
-- Users cannot directly edit role/plan/xp from the browser.
create or replace function public.create_task(p_title text,p_priority text default 'medium')
returns public.tasks
language plpgsql
security invoker
set search_path = public
as $$
declare
  new_task public.tasks;
  current_plan text;
  active_pro boolean;
  task_count integer;
begin
  if auth.uid() is null then raise exception 'Not authenticated'; end if;
  if length(trim(coalesce(p_title,''))) = 0 or length(trim(p_title)) > 200 then raise exception 'Invalid task title'; end if;
  if p_priority not in ('low','medium','high') then raise exception 'Invalid priority'; end if;
  select plan, pro_until > now() into current_plan, active_pro from public.profiles where id=auth.uid();
  select count(*) into task_count from public.tasks where user_id=auth.uid();
  if not coalesce(active_pro,false) and task_count >= 5 then raise exception 'Free plan task limit reached'; end if;
  insert into public.tasks(user_id,title,priority) values(auth.uid(),trim(p_title),p_priority) returning * into new_task;
  return new_task;
end;
$$;

grant execute on function public.create_task(text,text) to authenticated;

create or replace function public.set_task_completed(p_task_id bigint,p_completed boolean)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  was_completed boolean;
  xp_awarded integer := 0;
  new_xp integer;
begin
  select completed into was_completed from public.tasks where id=p_task_id and user_id=auth.uid() for update;
  if was_completed is null then raise exception 'Task not found'; end if;
  update public.tasks set completed=coalesce(p_completed,false) where id=p_task_id and user_id=auth.uid();
  if coalesce(p_completed,false) and not was_completed then
    update public.profiles set xp=xp+10 where id=auth.uid() returning xp into new_xp;
    xp_awarded := 10;
  else
    select xp into new_xp from public.profiles where id=auth.uid();
  end if;
  return jsonb_build_object('xp_awarded',xp_awarded,'xp',coalesce(new_xp,0));
end;
$$;

grant execute on function public.set_task_completed(bigint,boolean) to authenticated;

create table if not exists public.focus_rewards (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  rewarded_at timestamptz not null default now()
);

alter table public.focus_rewards enable row level security;
drop policy if exists "Users can view own focus rewards" on public.focus_rewards;
create policy "Users can view own focus rewards" on public.focus_rewards for select to authenticated using (auth.uid()=user_id);

create or replace function public.claim_focus_xp()
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  last_reward timestamptz;
  new_xp integer;
begin
  select rewarded_at into last_reward from public.focus_rewards where user_id=auth.uid() order by rewarded_at desc limit 1;
  if last_reward is not null and last_reward > now() - interval '25 minutes' then
    return jsonb_build_object('awarded',false,'xp_awarded',0);
  end if;
  insert into public.focus_rewards(user_id) values(auth.uid());
  update public.profiles set xp=xp+20 where id=auth.uid() returning xp into new_xp;
  return jsonb_build_object('awarded',true,'xp_awarded',20,'xp',new_xp);
end;
$$;

grant execute on function public.claim_focus_xp() to authenticated;

-- Helper: verify that current user is an admin.
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

grant execute on function public.is_admin() to authenticated;

-- Admin dashboard. SECURITY DEFINER is used so normal users cannot read everyone.
create or replace function public.admin_get_dashboard()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  if not public.is_admin() then
    raise exception 'Not authorized';
  end if;

  select jsonb_build_object(
    'stats', jsonb_build_object(
      'users', (select count(*) from public.profiles),
      'pending', (select count(*) from public.pro_requests where status='pending'),
      'approved', (select count(*) from public.pro_requests where status='approved'),
      'rejected', (select count(*) from public.pro_requests where status='rejected')
    ),
    'requests', coalesce((
      select jsonb_agg(x order by x.created_at desc)
      from (
        select
          r.id,r.user_id,r.payment_reference,r.status,r.created_at,
          p.name,
          u.email
        from public.pro_requests r
        left join public.profiles p on p.id=r.user_id
        left join auth.users u on u.id=r.user_id
        order by r.created_at desc
        limit 200
      ) x
    ),'[]'::jsonb)
  ) into result;

  return result;
end;
$$;

grant execute on function public.admin_get_dashboard() to authenticated;

-- Admin approval/rejection.
create or replace function public.admin_review_pro_request(
  p_request_id bigint,
  p_action text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  target_user uuid;
begin
  if not public.is_admin() then
    raise exception 'Not authorized';
  end if;

  if p_action not in ('approve','reject') then
    raise exception 'Invalid action';
  end if;

  select user_id into target_user
  from public.pro_requests
  where id=p_request_id and status='pending'
  for update;

  if target_user is null then
    raise exception 'Request not found or already reviewed';
  end if;

  update public.pro_requests
  set status = case when p_action='approve' then 'approved' else 'rejected' end,
      reviewed_at = now(),
      reviewed_by = auth.uid()
  where id=p_request_id;

  if p_action='approve' then
    update public.profiles
    set plan='pro',
        pro_until=greatest(coalesce(pro_until,now()),now()) + interval '30 days'
    where id=target_user;
  end if;
end;
$$;

grant execute on function public.admin_review_pro_request(bigint,text) to authenticated;

-- OPTIONAL: Run this AFTER you create your admin account.
-- This uses the email to find the account's UUID.
-- Change the email if needed.
--
-- update public.profiles p
-- set role='admin'
-- from auth.users u
-- where p.id=u.id
--   and u.email='youssiftarek177@gmail.com';

-- Recommended: make sure the admin role is actually set:
-- select p.id,u.email,p.role,p.plan
-- from public.profiles p
-- join auth.users u on u.id=p.id
-- where u.email='youssiftarek177@gmail.com';
